### ISSUE TITLE
RFE: results of SENTINEL_DEBUG=1 need to be timestamped

### ISSUE THREAD

**Issue by taw00** [nmarley/sentinel#29]
SENTINEL_DEBUG=1 will result in pageloads of very difficult to decypher data.    

It really needs to have a "Beginning run" "Ending run" log message and... each line desperately needs to be timestamped. If nothing else, timestamp the begin and end.

Thanks.

**Comment by nmarley** [comment]
All debug log entries are timestamped:

https://github.com/nmarley/sentinel/blob/master/lib/misc.py#L23-L24

Are you running the most recent version of the code?

**Comment by taw00** [comment]
Yes. Okay. Lemme rephrase it...
Log messages are _erratically_ timestamped.  Example, when you come back to this, and ask... "when did that happen" and can't answer it, it is less than ideal. :)

```
Invalid Masternode Status, cannot continue.
Invalid Masternode Status, cannot continue.
Invalid Masternode Status, cannot continue.
Invalid Masternode Status, cannot continue.
Invalid Masternode Status, cannot continue.
Invalid Masternode Status, cannot continue.
Invalid Masternode Status, cannot continue.
```

**Comment by nmarley** [comment]
The standard print messages are intended to be printed regardless of whether `SENTINEL_DEBUG` is set. These are "standard", (e.g. non-debug) messages, which should call a users's attention if running without DEBUG mode, and not intended to be log messages.
